### PR TITLE
1.0.3

### PR DESCRIPTION
**Pull request by mirkobrombin**

### CODE REVIEW

**Comment by hfiguiere** [comment]
congrats. you merged a PR that failed to build.

**Comment by hfiguiere** [comment]
using `git` URL as submodules is doomed to fail. And this is what happened here.

https://github.com/AtomsDevs/Atoms/blob/main/.gitmodules

**Comment by mirkobrombin** [comment]
> congrats. you merged a PR that failed to build.

I don't understand this emphasis on error.


> using `git` URL as submodules is doomed to fail. And this is what happened here.
> 
> https://github.com/AtomsDevs/Atoms/blob/main/.gitmodules

It has never failed before. Is it something new? If so, where can I read these news or the instructions to adapt my project?

**Comment by hfiguiere** [comment]
it worked by miracle here. It's not even specific to flathub.

As for the emphasis on no error, it is that a flatpak should be buildable. So builds are run on PR automatically. Sadly the CI blocking for merge is still in progress to be setup.

**Comment by mirkobrombin** [comment]
I built it on my own with success. So do I have to avoid git submodules? How can I adapt my project to be compatible with the buildbot?

**Comment by hfiguiere** [comment]
> I built it on my own with success. So do I have to avoid git submodules? How can I adapt my project to be compatible with the buildbot?

because you have your ssh key setup and a github account.
Change the submodules to use `https:` URL. Again this is not specific to flathub.

**Comment by mirkobrombin** [comment]
Thank you so much for pointing out the error and guiding me through it. Though I'd like to ask if the tone can be lowered in the future, as I felt like some of your comments were somewhat aggressive

**Pull request merged**
